export const GENERAL_ENABLE_LOADER = 'GENERAL_ENABLE_LOADER';
export const GENERAL_DISABLE_LOADER = 'GENERAL_DISABLE_LOADER';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';